### ISSUE TITLE
Upload field toggle doesn't display for logged out users

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-upload-file#16]
Logged in:
<img width="756" alt="screenshot 2016-10-04 15 22 26" src="https://cloud.githubusercontent.com/assets/2359131/19094703/6ff2ea54-8a46-11e6-814c-00ddbb1fcecf.png">

Logged out:
<img width="739" alt="screenshot 2016-10-04 15 23 13" src="https://cloud.githubusercontent.com/assets/2359131/19094715/7de34118-8a46-11e6-8c4d-742220984cb4.png">

**Comment by ghost1227** [comment]
Verified, for some reason the toggle itself fails. The JS _is_ being loaded, but the actual toggle fails. I'll dig into it and get an update pushed ASAP

**Comment by ghost1227** [comment]
Turns out this is because the toggle icon is a dashicon... and dashicons don't load if the user isn't logged in.

**Comment by SDavisMedia** [comment]
Oh goodness lol. That's crazy. Not a hard fix, at least!

**Comment by SDavisMedia** [comment]
Tested logged in/logged out on both checkout and purchase confirmation template. All is well on `issue/16`. :+1:
