### ISSUE TITLE
Remove S214_Debug class in favor of edd_debug_log

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-upload-file#33]
Since EDD core now has a built in logging function we should look to switching over to `edd_debug_log` instead of `S214_Debug`, so we can unify all the debugging.

**Comment by sunnyratilal** [comment]
Seems the only time where `S214_Debug` is relevant is to do with `qq.FineUploader` plugin where debug messages are displayed.

**Comment by sunnyratilal** [comment]
PR: #36 

@cklosowski Is there anywhere in the plugin, you want to see `edd_debug_log()` being used?

**Comment by cklosowski** [comment]
@sunnyratilal if it's not being used anywhere currently I don't know if we need to, but stripping out any references would be good.
